### ISSUE TITLE
Processing notification fails

### ISSUE THREAD

**Issue by Lasibian** [creamlike1024/EasyLPAC#19]
When EasyLPAC wants to processes a notification after installing, enabling or disabling a profile or it sends a command to LPAC like this:
`lpac.exe notification process 41 -r`

This needs to be changed to
`lpac.exe notification process -r 41`

Otherwise the command fails when the notification number is not 0.

For more details see my other thread at the lpac project:
https://github.com/estkme-group/lpac/issues/145

**Comment by TennousuAthena** [comment]
Please check if the [latest CI build](https://github.com/creamlike1024/EasyLPAC/actions/runs/10454596882) fixes this issue
The Windows build is included in `build-artifact-ubuntu`

**Comment by Lasibian** [comment]
Yes, that fixes it.

But I have one more little bug. After downloading a profile, the install notification is still shown in the `Notification` tab. This needs to be refreshed.

**Comment by creamlike1024** [comment]
fixed in 4f9e60c6c7b7e21bf906d0bc164de0066d8a6bc5
