### ISSUE TITLE
Problem when scanning and entering certain eSim profiles

### ISSUE THREAD

**Issue by cfegg** [creamlike1024/EasyLPAC#20]
The following problem occurs when scanning a QR-code or entering it manually certain eSim profiles from KeepGo and Firsty are not accepted when scanning and are incorrectly accepted when entering it manually. Here is the structure of the affected eSim profiles: 

LPA:1$dp-plus-par07-01.oasis-smartsim.com$16972-65675-56112-2T7TD$1.3.6.1.2.1.53860.7.5.1.1

The last sequence ......$1.3.6.1.2.1.53860.7.5.1.1
is not accepted when scanning the QR code and there is no option to enter it when entering it manually.

**Comment by Lasibian** [comment]
I'm not sure if this is already supported by the LPAC project that is used by EasyLPAC. I think you should check with them.

**Comment by creamlike1024** [comment]
This field is OID and only used to identify SM-DP+servers. It's not required during the profile download process. For details, please refer to the [GSMA SGP.22 RSP Technical Specification](https://www.gsma.com/esim/wp-content/uploads/2020/06/SGP.22-v2.2.2.pdf#page=111)
