### ISSUE TITLE
Can't open EasyLPAC on Windows 7

### ISSUE THREAD

**Issue by glli** [creamlike1024/EasyLPAC#27]
When I open the latest version of EasyLAPC (v0.7.6), nothing appears. After investigating via the command line, I encountered a 'bcryptprimitives.dll not found' error. It seems that the app was compiled using Go, and Go dropped support for Windows 7 starting with version 1.21.
Maybe consider supporting Windows 7 as System requirements say?

**Comment by creamlike1024** [comment]
The latest release(0.7.6 Build6) has been downgraded to Golang 1.20. Please check if it can run on Windows 7

**Comment by glli** [comment]
Confirm it is working on Windows 7 now.  Thank you so much!
