### ISSUE TITLE
`LpacErrDialog` will be popup three times if there's no card while click the refresh button

### ISSUE THREAD

**Issue by quul** [creamlike1024/EasyLPAC#7]
# Description
`LpacErrDialog` will be popup three times if there's no card while click the refresh button.

# Screenshots

https://github.com/creamlike1024/EasyLPAC/assets/56734434/98cb1518-8798-46df-9e03-c1453ee0b089

# Environment
EasyLPAC: 0.6.7
macOS: 14.2

# Dive into
It seems happes because of each function below call the `ShowLpacErrDialog` function
https://github.com/creamlike1024/EasyLPAC/blob/f567f7ba42d7bbca149182796f1e8f047faf30f2/control.go#L153-L155
But due to the lack knowledge of golang, I don't know which is the best practice, so I'm afraid I can't PR. :(
Anyway, just a little bug(

**Comment by creamlike1024** [comment]
Perhaps we need to stop subsequent refresh operations when errors occur

**Comment by creamlike1024** [comment]
Attempted to solve this bug
https://github.com/creamlike1024/EasyLPAC/blob/bd83666c23fb9ce1c575d5da2172cf3d45132e6a/control.go#L151-L172
